### ISSUE TITLE
error build version

### ISSUE THREAD

**Issue by taufikhidayat1993** [liplylie/ReactNativeChatImageAudio#2]
Could not resolve all dependencies for configuration ':app:_debugApk'.
   > A problem occurred configuring project ':react-native-sound'.
      > The SDK Build Tools revision (23.0.1) is too low for project ':react-native-sound'. Minimum required is 25.0.0

buil.gradel 
// Top-level build file where you can add configuration options common to all sub-projects/modules.

buildscript {
    repositories {
        jcenter()
        maven {
            url 'https://maven.google.com/'
            name 'Google'
        }
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:2.3.3'

        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}

allprojects {
    repositories {
        mavenLocal()
        jcenter()
        maven {
            // All of React Native (JS, Obj-C sources, Android binaries) is installed from npm
            url "$rootDir/../node_modules/react-native/android"
        }
        maven {
            url 'https://maven.google.com/'
            name 'Google'
        }
    }
}
ext {
    buildToolsVersion = "26.0.3"
    minSdkVersion = 16
    compileSdkVersion = 26
    targetSdkVersion = 26
    supportLibVersion = "26.1.0"
}

"please help me"

**Comment by liplylie** [comment]
here's a similar issue: https://github.com/oblador/react-native-keychain/issues/68
